import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/typescript/styles/Home.module.css";
import { GetStaticProps } from "next";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ org }: any) {
  return (
    <>
      {/* <Head>
        <title>Ciphery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className={styles.main}>
        <h1>{org.name}</h1>
        <p>Site: {org.url}</p>
        <p>Cargo: {org.bio}</p>
      </main>
    </>
  );
}
export const getStaticProps: GetStaticProps = async () => {
  const response = await fetch("https://api.github.com/users/gabriel-vict0r");
  const data = await response.json();
  return {
    props: {
      org: data,
    },
    revalidate: 10,
  };
};